WDP221202-22
kamilwilk95/wdp-2212 pull request #26
Opened 2022-12-13 21:01 UTC by pstanke

Zadaniem było stworzenie komponentu Promowane.

2022-12-13 22:11 UTC, djdrist approved these changes

2022-12-14 06:29 UTC, kamilwilk95 requested changes

2022-12-14 06:29 UTC, kamilwilk95 commented on src/components/common/ProductBoxTemplate/ProductBoxTemplate.js
> +            <Button variant='small'>
tą wewnętrzną część pojawiającą sie na hover proponuję zrobić jako osobny komponent, bedzie czytelniej

2022-12-14 09:58 UTC, pstanke commented on src/components/common/ProductBoxTemplate/ProductBoxTemplate.js
> +            <Button variant='small'>
Wydzielone do osobnych komponentów.

2022-12-14 11:30 UTC, Desmord approved these changes

2022-12-14 15:38 UTC, kamilwilk95 requested changes

2022-12-14 15:38 UTC, kamilwilk95 commented on src/components/common/HotDeals/HotDeals.js
> +
niepotrzebna linia przerwy

2022-12-14 15:38 UTC, kamilwilk95 commented on src/components/common/HotDeals/HotDeals.js
> +const HotDeals = () => {
po import dodaj linię przerwy

2022-12-14 15:38 UTC, kamilwilk95 commented on src/components/common/HotDeals/HotDealsHover/HotDealsHover.js
> +const HotDealsHover = () => {
Lepsza nazwa by byłą `HotDealsIcons` hover to zachowanie które w przyszłości moze ulec zmianie

2022-12-14 20:17 UTC, kamilwilk95 approved these changes

2022-12-15 15:38 UTC, merged