bug-WDP221202-29
kamilwilk95/wdp-2212 pull request #31
Opened 2022-12-16 18:02 UTC by Pawelsmolarski95

- zmieniłem nazwę komponentu Slider na BottomSlider
- dodałem paczke react-slick 
- dodałem Slider z paczki do komponentu BottomSlider
- dodałem style + RWD do Slider i BottomSlider 
- dodałem do styli plik ReactSlick.css (do ostylowania Slider-a) <- jeżeli da się jakoś inaczej to zrobić w głównych stylach bez osobnego pliku css chętnie się dowiem :)

2022-12-16 18:08 UTC, djdrist requested changes
Chyba nie wypushowałeś ostatecznego commita? Tu jest tylko jakiś z wczoraj dodający import useState i useSelector i tyle ;)

2022-12-16 18:40 UTC, Pawelsmolarski95 commented
> import

tak tak, miałem mały problem ale już powinno być dobrze:)

2022-12-16 19:05 UTC, djdrist requested changes
Jeśli przejedziesz sobie oknem przeglądarki przez cały zakres szerokości, to powinieneś zauważyć że pomiędzy jakoś 1200 a 1000px jest taka pusta strefa, gdzie znika już prawa strona a lewa nie wypełnia jeszcze całości ekranu.

Co do paczki zewnętrznej do miniaturek i sporo css do tego to nie wiem jak zapatruje się na to @kamilwilk95 ale teoretycznie można by to złożyć bez zewnętrznych paczek z wszystkiego co już mamy dostępne bo liczbę obrazków można by połączyć z trybem RWD w storze który mamy zaimplementowany i do tego reużyć część kodu od zmiany stron (kropek) i wymapować najpierw odpowiednią ilość elementów początową i na klik strzałki w lewo i na klik strzałki w prawo zrobić map na storze odpowiedniego zakresu elementów tak jak zmieniamy strony ;)

2022-12-17 08:00 UTC, Pawelsmolarski95 commented
> Jeśli przejedziesz sobie oknem przeglądarki przez cały zakres szerokości, to powinieneś zauważyć że pomiędzy jakoś 1200 a 1000px jest taka pusta strefa, gdzie znika już prawa strona a lewa nie wypełnia jeszcze całości ekranu.
> 
> Co do paczki zewnętrznej do miniaturek i sporo css do tego to nie wiem jak zapatruje się na to @kamilwilk95 ale teoretycznie można by to złożyć bez zewnętrznych paczek z wszystkiego co już mamy dostępne bo liczbę obrazków można by połączyć z trybem RWD w storze który mamy zaimplementowany i do tego reużyć część kodu od zmiany stron (kropek) i wymapować najpierw odpowiednią ilość elementów początową i na klik strzałki w lewo i na klik strzałki w prawo zrobić map na storze odpowiedniego zakresu elementów tak jak zmieniamy strony i do tego dodać swipe ;) I przy okazji załatwić część tasku następnego WDP221202-28

RWD pomiędzy 992px a 1199px poprawiona - dodałem mixin dla mniejszych ekranów.
Co do tego Slider-a to szczerze nie mogłem rozkminić jak to poskładać żeby wyglądało i działało dlatego użyłem paczki ale jak jest inny pomysł na to można spróbować:)

2022-12-17 13:20 UTC, Pawelsmolarski95 commented
Dodany stan activeImage i setActiveImage do komponentu GallerySlider i ten stan przekazuje do komponentów ImageSlider (wyświetlane zdjęcie)  i BottomSlider (onClick  - zmieniając stan po kliknięciu na zdjęcie)

2022-12-17 13:27 UTC, djdrist requested changes

2022-12-17 13:27 UTC, djdrist commented on src/components/common/GallerySlider/BottomSlider/BottomSlider.js
> +    console.log(image);
Jak już Ci nie potrzebny to wywal console'loga ;)

2022-12-17 13:27 UTC, djdrist commented on src/components/common/GallerySlider/GallerySlider.js
> +  const [activeImage, setActiveImage] = useState('bed_13.jpg');
Proponowałbym, żebyś zamiast obrazka dostał ID do stanu bo dzięki temu mógłbyś zmienić oprócz obrazka też nazwę, cenę i gwiazdki ;)

2022-12-17 16:18 UTC, djdrist approved these changes

2022-12-18 18:09 UTC, kamilwilk95 approved these changes

2022-12-18 18:09 UTC, merged