Add navigation
kamilwilk95/wdp-2212 pull request #33
Opened 2022-12-17 18:29 UTC by djdrist

2022-12-17 19:28 UTC, Pawelsmolarski95 approved these changes

2022-12-21 15:20 UTC, Desmord approved these changes

2022-12-28 10:15 UTC, kamilwilk95 requested changes
Sprawdź hover na linkach nawigacyjnych bo jest dość dziwny, napis znika i dopiero się pojawia.

Dodaj też obsługę stylowania aktywnego linku. Znajdź w dokumentacji react-router :)

2022-12-30 15:25 UTC, kamilwilk95 approved these changes

2022-12-30 15:26 UTC, merged