WDP221202-31
kamilwilk95/wdp-2212 pull request #36
Opened 2022-12-18 13:33 UTC by pstanke

Należało dodać funkcjonalność  do slidera z markami, tak aby strzałki przesuwały slider o tyle elementów, ile jest widoczne przy danej szerokości ekranu (np. w wersji desktop jest ich 6).

2022-12-18 17:26 UTC, Pawelsmolarski95 approved these changes

2022-12-18 17:59 UTC, kamilwilk95 requested changes

2022-12-18 17:59 UTC, kamilwilk95 commented on src/components/features/Brands/Brands.js
> +  for (let i = 0; i < brands.length; i += visibleElements[mode]) {
ten kod jest teraz wykonywany przy każdym renderowaniu komponentu Brands. Użyj useEffect

2022-12-18 17:59 UTC, kamilwilk95 commented on src/components/features/Brands/Brands.js
> +        <div onClick={() => nextPart()} className={`border m-3 ${styles.arrow}`}>
`onClick={nextPart}`

2022-12-18 17:59 UTC, kamilwilk95 commented on src/components/features/Brands/Brands.js
> +        <div onClick={() => prevPart()} className={`border m-3 ${styles.arrow}`}>
`onClick={prevPart}`

2022-12-19 19:19 UTC, kamilwilk95 approved these changes

2022-12-20 15:06 UTC, merged