task-WDP221202-44 & 37 - Add hook useProductsAction and add cart function
kamilwilk95/wdp-2212 pull request #37
Opened 2022-12-18 14:50 UTC by djdrist

Jak robiłem hooka to prościej było od razu zrobić też koszyk

2022-12-18 17:25 UTC, Pawelsmolarski95 approved these changes

2022-12-18 18:04 UTC, kamilwilk95 requested changes

2022-12-18 18:04 UTC, kamilwilk95 commented on src/components/common/HotDeals/HotDealsIcons/HotDealsIcons.js
> +    cartAction(props.id);
Ta nazwa nic nie mówi, może `addToCart`

2022-12-18 18:04 UTC, kamilwilk95 commented on src/components/common/ProductBoxTemplate/ProductBoxTemplate.js
> +  const { favoriteAction, compareAction } = useProductsAction();
`addToCompare`, `compareAction` będzie bardziej pasowaćkiedy faktycznie odpalimy porównanie

2022-12-18 18:04 UTC, kamilwilk95 commented on src/hooks/product-hook.js
> +import { useDispatch, useSelector } from 'react-redux';
`use-Product-action` będzie lepszą nazwą pliku, bo to faktycznie tutaj się znajduje

2022-12-21 15:26 UTC, Desmord approved these changes

2022-12-28 10:09 UTC, kamilwilk95 requested changes

2022-12-28 10:09 UTC, kamilwilk95 commented on src/components/common/ProductBoxTemplate/ProductBoxTemplate.js
> +    isCompared: isCompared,
można użyć destrukturyzacji i skróconego zapisu 
```
const product = {
    id,
    isFavorite,
    isCompared,
};
```

2022-12-30 15:48 UTC, pstanke approved these changes

2023-01-01 19:40 UTC, merged