WDP221202-36
kamilwilk95/wdp-2212 pull request #40
Opened 2022-12-20 18:25 UTC by Desmord

Stworzenie osobnego komponentu do wyświetlania kropek na stronie głównej.

2022-12-21 09:03 UTC, djdrist approved these changes

2022-12-28 10:05 UTC, kamilwilk95 requested changes

2022-12-28 10:05 UTC, kamilwilk95 commented on src/components/common/Dot/Dots.module.scss
> +.hotDealsDots {
Komponent generyczny powinien być idealnie napisany w taki sposób, aby go móc skopiować i wkleić do jakieś w ogóle innej aplikacji i nadal tam będzie działać. Tutaj w komponencie generycznym dodałeś mu bardzo specyficzny przypadek jakieś `hotDeals` i ktoś kto chce użyć `Dots` musi zdawać sobie sprawę co to jest `hotDeals` więc jak już, to takie coś powinno mieć uniwersalną nazwę opisującą jak to wpłynie na zachowanie tego komponentu. np. button active, jakieś wersjie small big itp.

Tutaj mamy specyficzne zachowanie w określonym miejscu na stronie i chodzi głównie o pozycjonowanie, to powinno być zrobione w inny sposób. Dots zawsze powinny wyświetlać się "normalnie". Jeśli jakiś komponent potrzebuje wyświetlić kropki w jakiś specyficzny sposób (absolutnie) to w tym komponencie należy zrobić np. `div` i jego ustawić gdzie trzeba a w środku wyświetlić `Dots`

2022-12-28 10:05 UTC, kamilwilk95 commented on src/components/common/Dot/Dots.module.scss
> +                display: block;
Wydaje mi się, że ten styl niczym nie różni się od tego wyżej więc nie jest potrzebny. To samo tyczy się ul i li

2022-12-28 10:05 UTC, kamilwilk95 commented on src/components/common/Dot/Dots.module.scss
> +        transform: translateY(15px);
W tym komponencie nie róbmy takich przesunieć, jeśli jest to konieczne to zróbmy to tak jak opisałem w komentarzu ponizej

2022-12-28 19:51 UTC, kamilwilk95 approved these changes

2022-12-28 19:51 UTC, merged