WDP221202-43
kamilwilk95/wdp-2212 pull request #44
Opened 2022-12-30 17:17 UTC by Pawelsmolarski95

- Dodałem wyświetlanie produktów dla kategorii z MenuBar

2022-12-30 18:24 UTC, pstanke approved these changes

2022-12-30 19:41 UTC, kamilwilk95 requested changes

2022-12-30 19:41 UTC, kamilwilk95 commented on src/components/views/ProductList/ProductList.js
> +            {categoryId === 'furniture'
taką logikę na razie usuń, nie obsługujemy tutaj żadnego podziału na kategorie

2022-12-30 19:41 UTC, kamilwilk95 commented on src/components/views/ProductList/ProductList.js
> +  const { categoryId } = useParams();
Nie przekazujemy w linku kategorii

2022-12-30 19:41 UTC, kamilwilk95 commented on src/components/views/ProductList/SingleProduct/SingleProduct.js
> +const SingleProduct = ({
MOże nazwij to `ProductListItem` żeby było wiadomo że to na liście produktów jest wyświetlanie

2022-12-30 19:41 UTC, kamilwilk95 commented on src/components/views/ProductList/SingleProduct/SingleProduct.js
> +  image: PropTypes.node,
string

2022-12-30 19:41 UTC, kamilwilk95 commented on src/components/views/ProductList/SingleProduct/SingleProduct.js
> +  name: PropTypes.node,
node?

2022-12-31 08:18 UTC, Pawelsmolarski95 commented
- poprawione PropTypes-y 
- zmieniono nazwę SingleProduct na ProductListItem
- usunięto logikę filtrowania

2022-12-31 12:56 UTC, pstanke approved these changes

2022-12-31 14:26 UTC, kamilwilk95 approved these changes

2022-12-31 14:26 UTC, merged