WDP221202-50
kamilwilk95/wdp-2212 pull request #47
Opened 2022-12-31 20:19 UTC by Pawelsmolarski95

- dodane sortowanie po wybranej opcji (cena/low/high + A-Z/Z-A)
- dodana zmiana ilości wyświetlanych elementów na stronie

2022-12-31 21:53 UTC, Pawelsmolarski95 commented
- dodałem obsługę przycisku "Load more"

2023-01-01 08:17 UTC, kamilwilk95 requested changes

2023-01-01 08:17 UTC, kamilwilk95 commented on src/components/views/ProductList/ProductList.js
> +              <Button
dodaj preventDefault żeby strony nie przewijało na górę

2023-01-01 09:10 UTC, Pawelsmolarski95 commented on src/components/views/ProductList/ProductList.js
> +              <Button
Button już poprawiony , nie przewija strony do góry

2023-01-01 19:38 UTC, kamilwilk95 approved these changes

2023-01-01 19:38 UTC, merged